/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FusionWrap */

#ifndef _Included_FusionWrap
#define _Included_FusionWrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FusionWrap
 * Method:    fusion_read
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_FusionWrap_fusion_1read
  (JNIEnv *, jclass, jstring);

/*
 * Class:     FusionWrap
 * Method:    fusion_write
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_FusionWrap_fusion_1write
  (JNIEnv *, jclass, jstring);

/*
 * Class:     FusionWrap
 * Method:    fusion_getattr
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_FusionWrap_fusion_1getattr
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
